from rest_framework import serializers

class SymptompsCovariablesRequest(serializers.Serializer):
	age	 = serializers.IntegerField()
	gender = serializers.CharField(max_length=50)
	asma = serializers.CharField(max_length=2)
	atralgias = serializers.CharField(max_length=2)
	cefalea = serializers.CharField(max_length=2)
	cianosis = serializers.CharField(max_length=2)
	conjuntivitis = serializers.CharField(max_length=2)
	diabetes = serializers.CharField(max_length=2)
	diarrea = serializers.CharField(max_length=2)
	disnea = serializers.CharField(max_length=2)
	dolor_abdominal = serializers.CharField(max_length=2)
	dolor_toracico = serializers.CharField(max_length=2)
	embarazada = serializers.CharField(max_length=2)
	enfermedad_cardiaca = serializers.CharField(max_length=2)
	epoc = serializers.CharField(max_length=2)
	escalofrios = serializers.CharField(max_length=2)
	fiebre = serializers.CharField(max_length=2)
	hipertension = serializers.CharField(max_length=2)
	inmunosupresion = serializers.CharField(max_length=2)
	insubis = serializers.CharField(max_length=2)
	insuf_renal_cronica = serializers.CharField(max_length=2)
	irritabilidad = serializers.CharField(max_length=2)
	mialgias = serializers.CharField(max_length=2)
	obesidad = serializers.CharField(max_length=2)
	odinogia = serializers.CharField(max_length=2)
	otra_condicion = serializers.CharField(max_length=2)
	polipnea = serializers.CharField(max_length=2)
	rinorea = serializers.CharField(max_length=2)
	tos = serializers.CharField(max_length=2)
	vacunado = serializers.CharField(max_length=2)
	vih = serializers.CharField(max_length=2)
	vomito = serializers.CharField(max_length=2)